version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres_typeorm_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data