version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres_typeorm_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "typeorm-auth"
    volumes:
      - ./data:/var/lib/postgresql/data